###register requests

POST http://localhost:3000/auth/register
content-type: application/json

{
    "username": "bbbbsb",
    "email": "bbbab@gmail.com",
    "mobile": "09199742134",
    "password": "123456789",
    "confirmPassword": "123456789"
}