###register request

POST http://localhost:3000/auth/register
content-type: application/json

{   
    "username": "mhakbarim",
    "email": "akbari@gmail.com",
    "mobile": "09190000000",
    "password": "admin123",
    "confirmPassword": "admin123"
}

###login request

POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "mhakbarim",
    "password": "admin123"
}